select
    r.run_id,
    coalesce(j.scenario_id, r.scenario_id) as scenario_id,
    r.scenario_id as optimizer_scenario_id,
    r.scenario_name,
    r.status as solver_status,
    r.termination_condition,
    r.planning_year,
    r.weather_year,
    r.snapshot_count,
    r.annualization_factor,
    r.objective_total_eur,
    r.annualized_capital_cost_eur,
    r.annualized_operating_cost_eur,
    r.demand_mwh,
    r.renewable_generation_mwh,
    r.renewable_generation_share,
    r.emissions_tco2,
    r.curtailment_mwh,
    r.unmet_demand_mwh,
    r.unmet_demand_share,
    r.solver_name,
    r.solver_version,
    r.model_version,
    r.engine_version,
    r.config_version,
    r.input_package_version,
    r.run_mode,
    r.calendar_mode,
    r.publication_state,
    case when j.status = 'failed' then false else r.is_current end as is_current,
    r.superseded_by_run_id,
    r.solve_duration_seconds,
    r.artifact_root,
    r.manifest_sha256,
    r.generated_at,
    r.published_at
from {{ source('optimization', 'optimization_runs') }} as r
left join {{ source('optimization', 'scenario_runs') }} as j
    on j.optimizer_run_id = r.run_id
